---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: express-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Replace with the correct storage class for your environment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 2  # Run the app on two nodes
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-container
        image: express-logging-backend:latest  # Ensure the image is available in a registry
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "500Mi"    # Minimum 500 MB
            cpu: "500m"        # Minimum 0.5 core
          limits:
            memory: "2Gi"      # Maximum 2 GB
            cpu: "2"           # Maximum 2 cores
        volumeMounts:
        - name: express-storage
          mountPath: /usr/src/app/data  # Mount 10GB of storage
      volumes:
      - name: express-storage
        persistentVolumeClaim:
          claimName: express-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  selector:
    app: express-app

