---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: express-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Replace with the correct storage class for your environment

